
with A as (SELECT LEVEL -1 AS HOUR
FROM DUAL CONNECT BY LEVEL <= 24), B as (SELECT HOUR, COUNT(HOUR) as 
COUNT
FROM(SELECT TO_NUMBER(TO_CHAR(DATETIME,'fmHH24')) as HOUR 
     FROM ANIMAL_OUTS )
GROUP BY HOUR
ORDER BY HOUR)

SELECT A.HOUR, nvl(B.Count, 0) as Count
FROM A LEFT OUTER JOIN B 
on  A.HOUR = B.HOUR
ORDER BY A.hour;

